spring:
  datasource:
    url: jdbc:mysql://8.130.96.6:3306/jxc_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: lzz
    password: Lzz4450..
  redis:
    host: localhost
    port: 6379

socket:
  hostname: localhost
  port: 12580

qiniu:
  access-key: 4COkwW6vGkzyxV5zNzWM9FQ3HGVM1CzH_4kefP65
  secret-key: _ar0eq1Cjyu65vATwHkjAOD8CTht1YDH_-oynxUI
  bucket: xunwu