version: '3'

services:
  # MySQL服务
  mysql:
    image: mysql:5.7
    container_name: jxc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jxc
      MYSQL_USER: jxc
      MYSQL_PASSWORD: jxc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis服务
  redis:
    image: redis:6.2
    container_name: jxc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 后端服务
  backend:
    build:
      context: ./java/local
      dockerfile: Dockerfile
    container_name: jxc-backend
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jxc?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=jxc
      - SPRING_DATASOURCE_PASSWORD=jxc
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: always

  # 前端服务
  frontend:
    build:
      context: ./vue/full
      dockerfile: Dockerfile
    container_name: jxc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
  redis_data: 