CREATE TABLE biz_special_equipment (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID，自增',
    uid INT NOT NULL COMMENT '用户ID，关联用户表',
    certificate_name VARCHAR(255) NOT NULL COMMENT '证书名称',
    equipment_type VARCHAR(100) NOT NULL COMMENT '设备类型',
    specifications VARCHAR(255) COMMENT '规格',
    factory_no VARCHAR(100) COMMENT '出厂编号',
    register_no VARCHAR(100) UNIQUE COMMENT '注册编号，唯一',
    usage_cert VARCHAR(255) COMMENT '使用证书',
    manager_name VARCHAR(255) COMMENT '设备管理人员姓名',
    manager_contact VARCHAR(20) COMMENT '设备管理人员联系方式',
    leader_name VARCHAR(255) COMMENT '主管领导姓名',
    leader_contact VARCHAR(20) COMMENT '主管领导联系方式',
    manufacturer VARCHAR(255) COMMENT '制造厂家',
    status ENUM('正常','维修','停用') COMMENT '设备状态',
    install_location VARCHAR(255) COMMENT '安装位置',
    use_date DATE COMMENT '使用日期',
    first_check DATE COMMENT '初次校验时间',
    last_check DATE COMMENT '最近一次校验时间',
    recheck_date DATE COMMENT '复检日期',
    alert_status ENUM('未设置', '待预警', '已提醒', '已关闭') COMMENT '预警状态',
    alert_count INT NULL COMMENT '预警次数',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '特种设备管理表'; 