-- 创建biz_three_level_training表（如果不存在）
DROP TABLE IF EXISTS `biz_three_level_training`;
CREATE TABLE `biz_three_level_training` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uid` int(11) DEFAULT NULL COMMENT '用户ID',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别',
  `age` int(11) DEFAULT NULL COMMENT '年龄',
  `phone` varchar(20) DEFAULT NULL COMMENT '电话',
  `original_job` varchar(100) DEFAULT NULL COMMENT '原工种',
  `current_job` varchar(100) DEFAULT NULL COMMENT '现工种',
  `join_date` datetime DEFAULT NULL COMMENT '入职日期',
  `id_number` varchar(20) DEFAULT NULL COMMENT '身份证号码',
  `company_train_date` date DEFAULT NULL COMMENT '公司级培训时间',
  `company_train_location` varchar(255) DEFAULT NULL COMMENT '公司级培训地点',
  `company_train_lecturer` varchar(50) DEFAULT NULL COMMENT '公司级培训主讲',
  `company_train_content` text COMMENT '公司级培训内容',
  `company_train_score` varchar(20) DEFAULT NULL COMMENT '公司级培训成绩',
  `workshop_train_date` date DEFAULT NULL COMMENT '车间级培训时间',
  `workshop_train_location` varchar(255) DEFAULT NULL COMMENT '车间级培训地点',
  `workshop_train_lecturer` varchar(50) DEFAULT NULL COMMENT '车间级培训主讲',
  `workshop_train_content` text COMMENT '车间级培训内容',
  `workshop_train_score` varchar(20) DEFAULT NULL COMMENT '车间级培训成绩',
  `team_train_date` date DEFAULT NULL COMMENT '班组级培训时间',
  `team_train_location` varchar(255) DEFAULT NULL COMMENT '班组级培训地点',
  `team_train_lecturer` varchar(50) DEFAULT NULL COMMENT '班组级培训主讲',
  `team_train_content` text COMMENT '班组级培训内容',
  `team_train_score` varchar(20) DEFAULT NULL COMMENT '班组级培训成绩',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_name` (`name`),
  KEY `idx_id_number` (`id_number`),
  KEY `idx_current_job` (`current_job`),
  KEY `idx_company_train_date` (`company_train_date`),
  KEY `idx_team_train_date` (`team_train_date`),
  KEY `idx_workshop_train_date` (`workshop_train_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='三级教育培训'; 